// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/data.ts
var BUYERS_PREMIUM = 0.14;
var COURSES = [
  {
    id: 1,
    name: "Fields Ranch East",
    loc: "Frisco \xB7 PGA HQ",
    desc: "PGA of America's championship-ready masterpiece. Firm, fast greens that punish mediocre approaches.",
    longDesc: "Home of the PGA of America's new headquarters, Fields Ranch East is a Gil Hanse design that has already hosted the KitchenAid Senior PGA Championship. Wide fairways invite aggressive play but the bentgrass greens \u2014 among the firmest and fastest in Texas \u2014 demand pinpoint approaches.",
    rack: 295,
    tag: "PGA HQ",
    yardage: 7868,
    par: 72,
    designer: "Gil Hanse",
    established: 2023,
    amenities: ["Caddie Service", "GPS Carts", "Practice Range", "Short Game Area", "PGA Coaching"]
  },
  {
    id: 2,
    name: "TPC Craig Ranch",
    loc: "McKinney \xB7 Tour Venue",
    desc: "Annual PGA Tour stop. Pure bentgrass greens, pristine conditioning year-round.",
    longDesc: "Host of the CJ CUP Byron Nelson, TPC Craig Ranch delivers a true Tour-caliber test. Tom Weiskopf's design weaves through native grasslands with strategic bunkering and water on 11 holes. The signature par-3 17th plays over a lake to a peninsula green.",
    rack: 245,
    tag: "Tour",
    yardage: 7468,
    par: 72,
    designer: "Tom Weiskopf",
    established: 2003,
    amenities: ["Tour-Grade Range", "Locker Room", "Fine Dining", "Pro Shop", "Forecaddies"]
  },
  {
    id: 3,
    name: "Cowboys Golf Club",
    loc: "Grapevine \xB7 Dallas",
    desc: "The only NFL-themed golf club in existence. Premium experience with Star-level hospitality.",
    longDesc: "The world's only NFL-themed golf club. Each hole tells a chapter of Dallas Cowboys history with memorabilia tee markers and a clubhouse that doubles as a Cowboys museum. The Jeff Brauer design plays through rolling hills with creek crossings and dramatic bunkering.",
    rack: 210,
    tag: "NFL",
    yardage: 7017,
    par: 72,
    designer: "Jeff Brauer",
    established: 2001,
    amenities: ["Cowboys Museum", "Concierge Caddies", "Premium Carts", "Steakhouse", "Cigar Lounge"]
  },
  {
    id: 4,
    name: "The Tribute",
    loc: "The Colony \xB7 Links",
    desc: "Links-style championship course inspired by the great Scottish and Irish seaside courses.",
    longDesc: "A loving tribute to the British Isles' greatest links. Holes are inspired by St Andrews, Royal Troon, Carnoustie, and Lahinch \u2014 pot bunkers, fescue rough, and burns included. Plays along Lewisville Lake giving genuine seaside winds.",
    rack: 195,
    tag: "Links",
    yardage: 7002,
    par: 72,
    designer: "Tripp Davis",
    established: 2e3,
    amenities: ["Lakeside Range", "Authentic Pot Bunkers", "Caddie Program", "Pub Clubhouse", "Fitting Studio"]
  }
];
var TEE_TIMES_BY_COURSE = {
  1: {
    date: "Sat Apr 5",
    slots: [
      { time: "6:42 AM", players: 4, bid: 310, bids: 4, endsIn: 4800 },
      { time: "7:14 AM", players: 4, bid: 340, bids: 7, endsIn: 5420 },
      { time: "7:46 AM", players: 4, bid: 325, bids: 5, endsIn: 6100 },
      { time: "8:18 AM", players: 2, bid: 290, bids: 3, endsIn: 7200 },
      { time: "9:22 AM", players: 4, bid: 315, bids: 6, endsIn: 9600 },
      { time: "10:30 AM", players: 4, bid: 285, bids: 2, endsIn: 12400 }
    ]
  },
  2: {
    date: "Fri Apr 4",
    slots: [
      { time: "6:18 AM", players: 4, bid: 240, bids: 5, endsIn: 1800 },
      { time: "6:50 AM", players: 4, bid: 260, bids: 9, endsIn: 2180 },
      { time: "7:22 AM", players: 4, bid: 255, bids: 6, endsIn: 2900 },
      { time: "8:04 AM", players: 2, bid: 230, bids: 3, endsIn: 3600 },
      { time: "9:08 AM", players: 4, bid: 250, bids: 4, endsIn: 5400 },
      { time: "11:14 AM", players: 4, bid: 215, bids: 2, endsIn: 12800 },
      { time: "1:42 PM", players: 4, bid: 195, bids: 1, endsIn: 21600 }
    ]
  },
  3: {
    date: "Sun Apr 6",
    slots: [
      { time: "7:00 AM", players: 4, bid: 220, bids: 3, endsIn: 11e3 },
      { time: "8:00 AM", players: 4, bid: 225, bids: 2, endsIn: 14400 },
      { time: "8:32 AM", players: 4, bid: 235, bids: 4, endsIn: 15200 },
      { time: "9:16 AM", players: 2, bid: 210, bids: 2, endsIn: 16800 },
      { time: "10:48 AM", players: 4, bid: 215, bids: 1, endsIn: 21600 }
    ]
  },
  4: {
    date: "Sat Apr 5",
    slots: [
      { time: "8:14 AM", players: 4, bid: 205, bids: 3, endsIn: 7200 },
      { time: "9:30 AM", players: 2, bid: 215, bids: 4, endsIn: 8600 },
      { time: "10:02 AM", players: 4, bid: 200, bids: 2, endsIn: 9800 },
      { time: "11:18 AM", players: 4, bid: 195, bids: 2, endsIn: 12e3 },
      { time: "12:50 PM", players: 2, bid: 185, bids: 1, endsIn: 18400 },
      { time: "2:24 PM", players: 4, bid: 175, bids: 1, endsIn: 24e3 }
    ]
  }
};
function findCourse(query) {
  if (typeof query === "number") return COURSES.find((c) => c.id === query);
  const q = String(query).trim().toLowerCase();
  const asId = Number(q);
  if (!Number.isNaN(asId)) {
    const byId = COURSES.find((c) => c.id === asId);
    if (byId) return byId;
  }
  return COURSES.find((c) => c.name.toLowerCase().includes(q) || c.loc.toLowerCase().includes(q));
}
function formatEndsIn(seconds) {
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  const h = Math.floor(seconds / 3600);
  const m = Math.round(seconds % 3600 / 60);
  return m ? `${h}h ${m}m` : `${h}h`;
}

// src/lib/mcp/tools/list-courses.ts
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List every golf course on the TeeStrike marketplace with its rack rate, location, and number of open tee time auctions.",
  inputSchema: {
    maxRackRate: z.number().positive().optional().describe("Only return courses whose rack rate per player is at or below this dollar amount.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ maxRackRate }) => {
    const courses = COURSES.filter((c) => maxRackRate ? c.rack <= maxRackRate : true).map((c) => ({
      id: c.id,
      name: c.name,
      location: c.loc,
      tag: c.tag,
      rackRate: c.rack,
      summary: c.desc,
      openAuctions: TEE_TIMES_BY_COURSE[c.id]?.slots.length ?? 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(courses, null, 2) }],
      structuredContent: { courses }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course details",
  description: "Get the full profile of one TeeStrike course: description, designer, yardage, par, amenities, rack rate, and its auction date.",
  inputSchema: {
    course: z2.string().min(1).describe("Course name (partial match allowed) or numeric course id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ course }) => {
    const found = findCourse(course);
    if (!found) {
      return { content: [{ type: "text", text: `No course matched "${course}".` }], isError: true };
    }
    const detail = {
      id: found.id,
      name: found.name,
      location: found.loc,
      tag: found.tag,
      rackRate: found.rack,
      summary: found.desc,
      description: found.longDesc,
      designer: found.designer,
      established: found.established,
      yardage: found.yardage,
      par: found.par,
      amenities: found.amenities,
      auctionDate: TEE_TIMES_BY_COURSE[found.id]?.date ?? null,
      openAuctions: TEE_TIMES_BY_COURSE[found.id]?.slots.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: { course: detail }
    };
  }
});

// src/lib/mcp/tools/list-tee-times.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_tee_times_default = defineTool3({
  name: "list_tee_times",
  title: "List tee time auctions",
  description: "List live tee time auctions with current bid, bid count, group size, and time remaining. Filter by course, group size, or how soon the auction closes.",
  inputSchema: {
    course: z3.string().optional().describe("Course name (partial match allowed) or id. Omit to search all courses."),
    players: z3.number().int().min(1).max(4).optional().describe("Only slots for this group size."),
    closingWithinHours: z3.number().positive().optional().describe("Only auctions closing within this many hours."),
    maxBid: z3.number().positive().optional().describe("Only auctions whose current bid per player is at or below this.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ course, players, closingWithinHours, maxBid }) => {
    const targets = course ? [findCourse(course)].filter(Boolean) : COURSES;
    if (course && targets.length === 0) {
      return { content: [{ type: "text", text: `No course matched "${course}".` }], isError: true };
    }
    const teeTimes = targets.flatMap((c) => {
      const entry = TEE_TIMES_BY_COURSE[c.id];
      if (!entry) return [];
      return entry.slots.filter((s) => players ? s.players === players : true).filter((s) => closingWithinHours ? s.endsIn <= closingWithinHours * 3600 : true).filter((s) => maxBid ? s.bid <= maxBid : true).map((s) => ({
        courseId: c.id,
        courseName: c.name,
        date: entry.date,
        time: s.time,
        players: s.players,
        currentBid: s.bid,
        bidCount: s.bids,
        rackRate: c.rack,
        vsRackPct: Math.round((s.bid / c.rack - 1) * 100),
        closesIn: formatEndsIn(s.endsIn)
      }));
    });
    return {
      content: [{ type: "text", text: JSON.stringify(teeTimes, null, 2) }],
      structuredContent: { teeTimes, count: teeTimes.length }
    };
  }
});

// src/lib/mcp/tools/estimate-bid.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var estimate_bid_default = defineTool4({
  name: "estimate_bid_cost",
  title: "Estimate bid cost",
  description: "Estimate the all-in cost of a TeeStrike bid: per-player bid, TeeStrike's 14% buyer's premium, group total, and how the bid compares to the course rack rate and the current leading bid.",
  inputSchema: {
    course: z4.string().min(1).describe("Course name (partial match allowed) or numeric course id."),
    bidPerPlayer: z4.number().positive().describe("Proposed bid amount per player, in dollars."),
    players: z4.number().int().min(1).max(4).default(4).describe("Number of players in the group."),
    time: z4.string().optional().describe("Optional tee time (e.g. '7:14 AM') to compare against that slot's leading bid.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ course, bidPerPlayer, players, time }) => {
    const found = findCourse(course);
    if (!found) {
      return { content: [{ type: "text", text: `No course matched "${course}".` }], isError: true };
    }
    const entry = TEE_TIMES_BY_COURSE[found.id];
    const slot = time ? entry?.slots.find((s) => s.time.toLowerCase() === time.trim().toLowerCase()) : void 0;
    const leadingBid = slot?.bid ?? (entry ? Math.max(...entry.slots.map((s) => s.bid)) : null);
    const premiumPerPlayer = Math.round(bidPerPlayer * BUYERS_PREMIUM * 100) / 100;
    const totalPerPlayer = Math.round((bidPerPlayer + premiumPerPlayer) * 100) / 100;
    const estimate = {
      course: found.name,
      teeTime: slot?.time ?? null,
      players,
      bidPerPlayer,
      buyersPremiumPerPlayer: premiumPerPlayer,
      allInPerPlayer: totalPerPlayer,
      groupTotal: Math.round(totalPerPlayer * players * 100) / 100,
      rackRate: found.rack,
      vsRackPct: Math.round((bidPerPlayer / found.rack - 1) * 100),
      leadingBid,
      leadsCurrentBid: leadingBid === null ? null : bidPerPlayer > leadingBid
    };
    return {
      content: [{ type: "text", text: JSON.stringify(estimate, null, 2) }],
      structuredContent: { estimate }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jikemqgqkldqrxjeddxg";
var mcp_default = defineMcp({
  name: "teestrike",
  title: "TeeStrike",
  version: "0.1.0",
  instructions: "Tools for TeeStrike, a premium golf tee time auction marketplace in the Dallas\u2013Fort Worth area. Use `list_courses` to browse courses, `get_course` for a full course profile, `list_tee_times` to find live tee time auctions (filterable by course, group size, closing window, and max bid), and `estimate_bid_cost` to price a bid including the 14% buyer's premium.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, get_course_default, list_tee_times_default, estimate_bid_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
